# -*- coding: utf-8 -*-
import re

SRC = '/mnt/agents/output/app/index.html'
DST = '/mnt/agents/output/app/index-en.html'

TR_SIMPLE = [
# nav / intro
("Chi Siamo", "About Us"),
("Servizi", "Services"),
("Sposa", "Bridal"),
("Galleria", "Gallery"),
("Contatti", "Contact"),
('Salta intro <i class="fas fa-chevron-right"></i>', 'Skip intro <i class="fas fa-chevron-right"></i>'),
# home
("La tua bellezza,<br><span>la nostra arte</span>", "Your beauty,<br><span>our art</span>"),
("Un'esperienza di lusso su misura per te. Taglio, colore e trattamenti firmati MZ Parrucchieri.",
 "A luxury experience tailored to you. Cuts, color and treatments by MZ Parrucchieri."),
("Scopri i servizi e prenota", "Discover our services and book"),
# chi siamo
("La nostra storia", "Our story"),
("Chi <span>Siamo</span>", "Who <span>We Are</span>"),
("Eccellenza e passione dal 2004", "Excellence and passion since 2004"),
("Scegli il tuo salone e prenota", "Choose your salon and book"),
('<i class="fas fa-star" style="margin-right:8px"></i> Dal 2004',
 '<i class="fas fa-star" style="margin-right:8px"></i> Since 2004'),
("Fondatore & Creative Director", "Founder &amp; Creative Director"),
("Dove trovarci", "Where to find us"),
("Le nostre <span>Sedi</span>", "Our <span>Locations</span>"),
("Quattro saloni, un'unica eccellenza", "Four salons, one excellence"),
# staff
("Il nostro team", "Our team"),
("Gli <span>Artisti</span>", "The <span>Artists</span>"),
("Professionisti dedicati alla tua bellezza", "Professionals dedicated to your beauty"),
# servizi
("Listino prezzi 2026", "2026 Price List"),
("Servizi & <span>Tariffe</span>", "Services &amp; <span>Pricing</span>"),
("Ogni salone ha il suo listino: scegli la sede, scopri i prezzi e prenota direttamente",
 "Each salon has its own price list: choose your location, discover the prices and book directly"),
("Taglio & Piega", "Cut &amp; Blow-dry"),
("Colore & Effetti", "Color &amp; Effects"),
("Trattamenti", "Treatments"),
("Capelli", "Hair"),
("Barba", "Beard"),
("Ricostruzione del Capello", "Hair Reconstruction"),
("Trattamento Ristrutturante", "Restructuring Treatment"),
("Stiratura Cheratinica", "Keratin Straightening"),
("Arcata Sopraccigliare · Depilazione", "Eyebrows · Waxing"),
("Colore No Ammoniaca", "Ammonia-Free Color"),
("Trattamento Curativo", "Repair Treatment"),
("Ricostruzione Olaplex", "Olaplex Reconstruction"),
("Ricostruzione Nashi", "Nashi Reconstruction"),
("Taglio Ragazzo 13-17", "Boys' Cut 13-17"),
("Taglio Uomo over 18", "Men's Cut 18+"),
("Arcata Sopraccigliare", "Eyebrow Shaping"),
("Taglio Uomo Laterali", "Men's Cut (sides)"),
("Taglio Donna Maury", "Women's Cut by Maury"),
("Taglio Bimbo 0-14 anni", "Kids' Cut 0-14"),
("Permanente / Ondulazione", "Perm / Waves"),
("Rifilatura Barba", "Beard Trim"),
("Barba Rifilatura", "Beard Trim"),
("Colore Moda", "Fashion Color"),
("Ritocco Colore", "Color Touch-up"),
("Effetti Luce", "Light Effects"),
("Piega Lunga", "Long Hair Blow-dry"),
("Acconciatura", "Updo"),
("Taglio Donna", "Women's Cut"),
("Taglio Bimbo 0-12", "Kids' Cut 0-12"),
("Taglio Uomo", "Men's Cut"),
("Riflessante", "Color Gloss"),
("Lucidante", "Shine Treatment"),
("Permanente", "Perm"),
("Piega", "Blow-dry"),
("Barba Spa", "Spa Beard Ritual"),
("Trucco", "Make-up"),
("secondo quantita'", "by quantity"),
("da 15 a 85 €", "from 15 to 85 €"),
("da 50 a 60 €", "from 50 to 60 €"),
("da 17 a 30 €", "from 17 to 30 €"),
("da 15 a 65 €", "from 15 to 65 €"),
("Listini 2026 ufficiali MZ Parrucchieri · I prezzi possono variare in base a lunghezza e quantita' · Per un preventivo preciso chiama la tua sede",
 "Official MZ Parrucchieri 2026 price lists · Prices may vary according to hair length and quantity · For an exact quote, call your salon"),
# galleria
("Il nostro <span>Lavoro</span>", "Our <span>Work</span>"),
("Una selezione curata: mostriamo solo il meglio", "A curated selection: only our best"),
("Le foto più artistiche", "Our most artistic shots"),
("Tagli, barba e rasatura", "Cuts, beard and shaves"),
("Ambienti e atmosfera", "Spaces and atmosphere"),
("Sfumatura al Sole", "Sun-Kissed Balayage"),
("Onde Rame", "Copper Waves"),
("Laura al Lavoro", "Laura at Work"),
("Movimento Naturale", "Natural Movement"),
("Rosso Intenso", "Intense Red"),
("L'Arte del Colore", "The Art of Color"),
("Biondo Luminoso", "Luminous Blonde"),
("Raccolto Romantico", "Romantic Updo"),
("Rosa e Blu", "Pink and Blue"),
("Il Tocco Finale", "The Finishing Touch"),
("Onde Dorate", "Golden Waves"),
("Taglio di Precisione", "Precision Cut"),
("Biondo Seta", "Silky Blonde"),
("Maurizio, il Maestro", "Maurizio, the Master"),
("Bob Ramato", "Copper Bob"),
("Passione in Salone", "Passion in the Salon"),
("Chioma Bruna", "Brunette Mane"),
("Rosa e il Colore", "Rosa and Color"),
("Riflessi Caramello", "Caramel Highlights"),
("Riccio Sculpt", "Sculpted Curls"),
("La Palette", "The Palette"),
("Bob Lavanda", "Lavender Bob"),
("Meches in Corso", "Highlights in Progress"),
("Argento", "Silver"),
("Ricci Naturali", "Natural Curls"),
("Bob Castano", "Brown Bob"),
("Treccia in Opera", "Braid in the Making"),
("Nero Lucente", "Glossy Black"),
("Trucco Sposa", "Bridal Make-up"),
("Balayage Biondo", "Blonde Balayage"),
("Fade Perfetto", "Perfect Fade"),
("Onde Corte", "Short Waves"),
("Dettaglio Labbra", "Lip Detail"),
("Curly Corto", "Short Curly"),
("Liscio Setoso", "Silky Straight"),
("Volume Riccio", "Curly Volume"),
("Trecce Boxer", "Boxer Braids"),
("Fade e Riccio", "Fade and Curls"),
("Taper Classico", "Classic Taper"),
("Fade con Ciuffo", "Fade with Fringe"),
("Riccio Naturale", "Natural Curl"),
("Biondo Ghiaccio", "Ice Blonde"),
("Mullet Moderno", "Modern Mullet"),
("Linee Pulite", "Clean Lines"),
("Rasatura Tradizionale", "Traditional Shave"),
("Rasoio a Mano Libera", "Straight Razor"),
("Barba Scolpita", "Sculpted Beard"),
("In Poltrona", "In the Chair"),
("Mullet e Barba", "Mullet and Beard"),
("La Reception", "The Reception"),
("Forbice e Pettine", "Scissors and Comb"),
("Dettagli di Precisione", "Precision Details"),
("Il Lavaggio", "The Wash"),
("Al Lavoro", "At Work"),
("Il Salone", "The Salon"),
("L'Atmosfera", "The Atmosphere"),
("Acconciature", "Hairstyling"),
("Colore Creativo", "Creative Color"),
("Colore", "Color"),
("Taglio", "Cut"),
("Uomo", "Men"),
("Romantico", "Romantic"),
("Naturale", "Natural"),
("Classico", "Timeless"),
("Emozioni", "Emotions"),
("Momenti", "Moments"),
("Ambiente", "Atmosphere"),
("Dettagli", "Details"),
("In Salone", "In the Salon"),
# contatti
("Contattaci", "Contact Us"),
("Prenota la tua <span>Consulenza</span>", "Book your <span>Consultation</span>"),
("Siamo pronti ad ascoltarti e a realizzare la tua bellezza",
 "We are ready to listen to you and create your beauty"),
('Informazioni <span style="color:var(--gold)">e orari</span>',
 'Information <span style="color:var(--gold)">&amp; hours</span>'),
("Prenotazioni", "Bookings"),
("Orari", "Hours"),
("Ogni sede ha i propri orari: li trovi nella pagina Servizi accanto al listino",
 "Each location has its own hours: find them on the Services page next to the price list"),
("Chiuso", "Closed"),
("Domenica in tutte le sedi", "Sundays at all locations"),
("Sedi", "Locations"),
("Prenota subito", "Book Now"),
("Chiama ora", "Call Now"),
# make up
("Make Up<br><span>Professionale</span>", "Professional<br><span>Make Up</span>"),
("Prenota il tuo make up", "Book your make-up"),
("L'arte del trucco", "The art of make-up"),
("Rivelare la tua <span>bellezza</span>", "Reveal your <span>beauty</span>"),
("Ogni volto racconta una storia unica", "Every face tells a unique story"),
("Trucco Sposa", "Bridal Make-up"),
("Cerimonia & Eventi", "Ceremony &amp; Events"),
("Trucco Fotografico", "Photographic Make-up"),
("Sera & Gala", "Evening &amp; Gala"),
("Prodotti Professionali", "Professional Products"),
("Consulenza su Misura", "Tailored Consultation"),
("Per Ogni Occasione", "For Every Occasion"),
("Galleria <span>Make Up</span>", "Make Up <span>Gallery</span>"),
("Ispirazioni", "Inspiration"),
("I nostri lavori, la tua bellezza", "Our work, your beauty"),
("La Sposa", "The Bride"),
("Labbra Protagoniste", "Statement Lips"),
("Il Risultato Finale", "The Final Result"),
("Sfumature Nude", "Nude Shades"),
("Onde Luminose", "Luminous Waves"),
("Prenota la tua consulenza make up personalizzata nei nostri saloni.",
 "Book your personalized make-up consultation at our salons."),
("Pronta a <span>brillare</span>?", "Ready to <span>shine</span>?"),
("Prenota ora la tua prova", "Book Your Trial Now"),
# sposa
("Il tuo giorno speciale", "Your special day"),
("Acconciature<br><span>da Sposa</span>", "Bridal<br><span>Hairstyles</span>"),
("Consulenza bridal", "Bridal consultation"),
("La tua <span>acconciatura</span> perfetta", "Your perfect <span>hairstyle</span>"),
("Ogni sposa merita un look unico e memorabile", "Every bride deserves a unique and memorable look"),
("Accessori Luminosi", "Radiant Accessories"),
("Il Velo Perfetto", "The Perfect Veil"),
("Il Velo", "The Veil"),
("Attenzione ai Dettagli", "Attention to Detail"),
("Galleria <span>Sposa</span>", "Bridal <span>Gallery</span>"),
("Bouquet Pastello", "Pastel Bouquet"),
("In Giardino", "In the Garden"),
("Eleganza Senza Tempo", "Timeless Elegance"),
("La Gioia del Giorno", "The Joy of the Day"),
("Treccia allo Specchio", "Braid by the Mirror"),
("La Piccola Damigella", "The Little Bridesmaid"),
("Velo in Pizzo", "Lace Veil"),
("Verso la Cerimonia", "Toward the Ceremony"),
("La Preparazione", "The Preparation"),
("Make-up Occhi", "Eye Make-up"),
("Lo Specchio", "The Mirror"),
("Sorriso nella Natura", "A Smile in Nature"),
("Selfie con la Sposa", "Selfie with the Bride"),
("Attesa Elegante", "Elegant Anticipation"),
("Pronta al Sì", "Ready to Say Yes"),
("Fissaggio Perfetto", "Perfect Finishing"),
("Make-up al Lavoro", "Make-up at Work"),
("Sorriso allo Specchio", "Smile in the Mirror"),
("Il tuo giorno piu' <span>bello</span> merita il meglio", "Your most <span>beautiful</span> day deserves the best"),
# footer / cookie
("Prenota", "Book Now"),
("Prenota prova acconciatura", "Book a Hairstyling Trial"),
("Acconciature da sogno per il tuo giorno speciale", "Dream hairstyles for your special day"),
("Metodi di pagamento accettati", "Accepted Payment Methods"),
("Seguici", "Follow Us"),
("Rifiuta", "Decline"),
("Accetta", "Accept"),
("Ultimo aggiornamento: Agosto 2026", "Last updated: August 2026"),
("Privacy &amp; Trasparenza", "Privacy &amp; Transparency"),
("Cosa sono i <span>cookie</span>", "What <span>cookies</span> are"),
("Cookie utilizzati da <span>questo sito</span>", "Cookies used by <span>this website</span>"),
("Servizi e contenuti di <span>terze parti</span>", "Third-party <span>services and content</span>"),
("Come gestire i <span>cookie</span>", "How to manage <span>cookies</span>"),
("Titolare del <span>trattamento</span>", "Data <span>Controller</span>"),
("Modifiche a questa <span>informativa</span>", "Changes to this <span>policy</span>"),
# wedding awards
("Riconoscimenti", "Recognition"),
("recensioni autentiche", "authentic reviews"),
("valutazione massima", "top rating"),
("anni consecutivi", "consecutive years"),
]

# specials: attributes + text preceded by icons
TR_SPECIAL = [
('placeholder="Il tuo nome"', 'placeholder="Your name"'),
('placeholder="La tua email"', 'placeholder="Your email"'),
('placeholder="Il tuo telefono"', 'placeholder="Your phone"'),
('placeholder="Scrivici un messaggio..."', 'placeholder="Write us a message..."'),
("</i> Lun-Sab · Mer fino 21:00<", "</i> Mon-Sat · Wed until 9:00 PM<"),
("</i> Mar-Sab 8:30-19:30 · Mer fino 20:30<", "</i> Tue-Sat 8:30 AM-7:30 PM · Wed until 8:30 PM<"),
("</i> Mar-Sab 9:00-18:30 · Mer fino 20:30<", "</i> Tue-Sat 9:00 AM-6:30 PM · Wed until 8:30 PM<"),
("</i> Mar-Ven 9:30-19:30 · Sab 9:00-18:00<", "</i> Tue-Fri 9:30 AM-7:30 PM · Sat 9:00 AM-6:00 PM<"),
("</i> Prenota · ", "</i> Book · "),
("</i> Invia richiesta<", "</i> Send Request<"),
("</i> Raggiungici</a>", "</i> Get Directions</a>"),
("</i> Carte</span>", "</i> Cards</span>"),
("Scopri le recensioni <i", "Read the reviews <i"),
('alt="Attestato Wedding Awards 2025 - MZ Parrucchieri vincitore su matrimonio.com"',
 'alt="Wedding Awards 2025 Certificate - MZ Parrucchieri winner on matrimonio.com"'),
]

# element-level long paragraphs (tag, distinctive, new inner)
TR_ELEM = [
("p", "non e' un semplice salone",
 '<span class="highlight">MZ Parrucchieri</span> is not just a salon. We are an image studio where a passion for hairstyling meets personalized consultation. Every cut and color is designed to enhance your uniqueness, in a refined and private setting.'),
("p", "Crediamo che la bellezza",
 "We believe that beauty is an art and that every client deserves a tailor-made experience, built on listening, expertise and the highest-quality products. Our salons are spaces where time stands still and well-being takes center stage."),
("p", "20 anni di esperienza",
 "With over <strong>20 years of experience</strong>, founder <strong>Maurizio Zucchini</strong> has turned his passion into a recognized excellence, building teams of professionals constantly trained on the latest international trends."),
("p", "Sin dall'eta'",
 "Certain since the age of <strong>14</strong> that he wanted to turn his passion into a profession, Maurizio devoted his long years of study to quality. After training at Palmer, he deepened his knowledge of women's hairdressing, moving between <strong>London, Chicago and Italy</strong>."),
("p", "Ha aperto il primo salone",
 "He opened the first MZ salon in <strong>2004</strong>, the second in <strong>2014</strong>, the third in <strong>2020</strong> and the fourth in <strong>2022</strong>. Master trainer for Pivot Point, one of the world leaders in hairdresser education."),
("p", "Al suo percorso si affianca",
 "Alongside his journey stands a long-established collaboration with <strong>Nashi Argan</strong>, an Italian excellence in beauty care, which sees him as trainer and educator first across the region and today throughout Italy."),
("p", "nasce dall'anima interiore",
 '<em style="color:var(--gold)">"The beauty of every person is born from the inner soul and knows no boundaries."</em>'),
("p", "troverete <strong>Eleonora",
 "In Villanova di Castenaso, near Bologna, you will find <strong>Eleonora, Cinzia, Fabiana, Melissa, Alessandra and Rosa</strong>, ready to welcome you! A professional hairdressing staff thanks to the experience gained over the years."),
("p", "un luogo dove sentirti a casa",
 "We are in Villafontana di Medicina, a place where you can feel at home while we take care of your hair. You will find <strong>Barbara, the two Lauras and Veronica</strong>, professional and highly qualified, passionate about women's total looks with special attention to the latest trends."),
("p", "un gruppo affiatato",
 "In our Imola salon you will find <strong>Carmine and Luigi</strong>, a close-knit and highly skilled team thanks to decades of experience, curiosity, constant training and the drive to always keep pace with — if not ahead of — the latest trends. Color, cut, highlights, facial aesthetics: everything tailored to you!"),
("p", "sempre pronti ad allinearsi",
 'At the Barber Shop in Medicina you will find <strong>Gabriele, Daniele and Mirco</strong>, always ready to keep up with the new trends in men\'s grooming. Long beards, short beards, groomed with the utmost care, and relaxing shaves with hot and cold towel compresses: a true ritual for men, without neglecting hair care, from clipper cuts to classic <em style="color:var(--gold)">old school</em> scissor-and-comb work.'),
("p", "Lun 10-18",
 '<i class="fas fa-location-dot"></i> Via Cesare Battisti 6, Villanova di Castenaso<br><i class="far fa-clock"></i> Mon 10 AM-6 PM · Tue-Fri 9:00 AM-7:30 PM (Wed until 9:00 PM) · Sat 8 AM-6 PM'),
("p", "Mar-Ven 8:30-19:30",
 '<i class="fas fa-location-dot"></i> Piazza Bersani 17, Villafontana di Medicina<br><i class="far fa-clock"></i> Tue-Fri 8:30 AM-7:30 PM (Wed until 8:30 PM) · Sat 8 AM-6 PM'),
("p", "Mercoledi' fino alle 20:30",
 '<i class="fas fa-location-dot"></i> Piazza Gramsci 10, Imola<br><i class="far fa-clock"></i> Tue-Sat 9:00 AM-6:30 PM · Wednesdays until 8:30 PM'),
("p", "Argentesi 22, Medicina (BO)",
 '<i class="fas fa-location-dot"></i> Via O. Argentesi 22, Medicina (BO)<br><i class="far fa-clock"></i> Tue-Fri 9:30 AM-7:30 PM · Sat 9:00 AM-6:00 PM'),
("p", "tra i vincitori dei Wedding Awards",
 "MZ Parrucchieri is among the winners of the Wedding Awards by matrimonio.com, Italy's No.1 wedding portal: an honour awarded to the most reviewed and best rated companies, chosen by couples of brides and grooms."),
("p", "Un premio che nasce dalle vostre parole",
 "An award born from your words: over 100 authentic reviews and the highest rating, earned bride after bride, year after year."),
("p", "Il trucco come forma d'arte",
 "Make-up as an art form: in our salons every face becomes a precious canvas, where femininity and authenticity emerge in all their light."),
("p", "molto piu' di un trucco",
 "For us, make-up is <strong>much more than makeup</strong>: it is a tailor-made beauty ritual, designed around the features, the light and the personality of every woman."),
("p", "il marchio professionale nato per il palcoscenico",
 "In our salons we exclusively use <strong>MAKE UP FOR EVER</strong> products, the professional brand born for the stage, to give every client high performance and a flawless result that lasts over time."),
("p", "far emergere da ogni donna",
 "Our goal is only one: to bring out every woman's own side of <em>femininity and authenticity</em>."),
("p", "formule ad alta performance",
 "Only MAKE UP FOR EVER: high-performance formulas, extreme hold and a flawless finish in every light, from day to night."),
("p", "armonia cromatica",
 "Facial analysis, color harmony and texture selection: every look is born from listening and enhances your features."),
("p", "resiste alle emozioni",
 "Brides, ceremonies, photo shoots and events: a look that withstands emotions and the spotlight."),
("p", "Ogni ciocca racconta",
 "For the most beautiful day of your life, trust the expert hands of MZ Parrucchieri. Every strand tells a love story."),
("p", "l'acconciatura e' fondamentale",
 "For your most beautiful day, <strong>your hairstyle is essential</strong>. The first thing to consider when choosing a hairstyle, whether bridal or in general, is the <em>shape of the face</em>."),
("p", "la parola d'ordine",
 "When it comes to bridal hairstyles, the watchword is <strong>simplicity</strong>: hair up or half-up, the important thing is that it looks as natural as possible."),
("p", "stile acqua e sapone",
 "No longer in fashion is loose, tousled hair, but well-gathered styles studied in every detail: a <em>fresh, natural look</em> that is in any case very polished."),
("p", "grandi fiori molto vistosi",
 "The current trend features large, eye-catching flowers and luminous tiaras full of Swarovski crystals for a fairytale effect."),
("p", "Sempre ben accetto",
 "Always welcome, as tradition dictates — perfect if it is long, lightly pinned to the hairstyle and flowing down the body."),
("p", "non tralasciare nulla",
 "On your wedding day, leave nothing to chance. Every detail counts for an impeccable, timeless look."),
("p", "Prova acconciatura inclusa",
 "Book a personalized bridal consultation at one of our salons.<br>Hairstyling trial included to find the perfect look for you."),
("p", "L'arte della bellezza",
 '&copy; 2026 MZ Parrucchieri - The art of beauty &middot; <a onclick="navigateTo(\'cookie-policy\')" style="color:inherit;cursor:pointer;text-decoration:none;transition:color 0.4s" onmouseover="this.style.color=\'var(--gold)\'" onmouseout="this.style.color=\'inherit\'">Cookie Policy</a>'),
("p", "piccoli file di testo",
 "Cookies are small text files that websites save on your device while you browse. They are used to ensure the site works properly, to remember your preferences and, in some cases, to collect statistical or profiling information."),
("p", "utilizza esclusivamente",
 "The <strong>MZ Parrucchieri</strong> website uses exclusively <strong>technical cookies</strong>, which are essential for the pages to function and do not require your prior consent:"),
("p", "Nessun cookie di profilazione",
 "<strong>No profiling or tracking cookies</strong> are installed by this site: we do not collect browsing statistics nor do we create user profiles."),
("p", "si collega ad alcuni servizi esterni",
 "To offer you a complete experience, the site connects to a few external services that may install their own cookies according to their respective policies:"),
("p", "informative privacy di questi servizi",
 "We invite you to consult the privacy policies of these services for more details on their data processing."),
("p", "modificare le tue preferenze o eliminare i cookie",
 "You can change your preferences or delete cookies at any time directly from your browser settings:"),
("p", "La disabilitazione dei cookie tecnici",
 "Disabling technical cookies may compromise some features of the site."),
("p", "Il titolare del trattamento dei dati",
 "The data controller is <strong>MZ Parrucchieri</strong>, with salons in Villanova di Castenaso (Via Cesare Battisti 6), Villafontana di Medicina (Piazza Bersani 17), Imola and Barber Shop Medicina (Via O. Argentesi 22). For any information you can contact us using the details on the Contact page."),
("p", "aggiornata periodicamente",
 "This Cookie Policy may be updated periodically. We invite you to check this page to verify any changes."),
("p", "Questo sito utilizza solo",
 'This site uses only <strong>technical cookies</strong> to guarantee you the best browsing experience — no profiling cookies. You can accept or decline: your choice will be remembered. <a onclick="navigateTo(\'cookie-policy\')">Read the Cookie Policy</a>'),
("li", "Cookie di navigazione:",
 "<strong>Navigation cookies:</strong> they enable the correct display of the site's pages and features."),
("li", "Preferenza sul consenso:",
 "<strong>Consent preference:</strong> your choice in the cookie banner (accept or decline) is stored locally on your device, so the banner is not shown again on every visit."),
("li", "Google Fonts e Font Awesome:",
 "<strong>Google Fonts and Font Awesome:</strong> for the site's typography and icons."),
("li", "Instagram e Facebook:",
 "<strong>Instagram and Facebook:</strong> through the links to our official profiles in the footer."),
("li", "WhatsApp e Google Maps:",
 "<strong>WhatsApp and Google Maps:</strong> through the contact buttons and the directions to our salons."),
("li", "Chrome:",
 "<strong>Chrome:</strong> Settings &gt; Privacy and security &gt; Cookies"),
("li", "Safari:",
 "<strong>Safari:</strong> Preferences &gt; Privacy"),
("li", "Firefox:",
 "<strong>Firefox:</strong> Settings &gt; Privacy &amp; security"),
("li", "Edge:",
 "<strong>Edge:</strong> Settings &gt; Cookies and site permissions"),
]

# ============ RUNNER ============
html = open(SRC, encoding='utf-8').read()
misses = []

for old, new in TR_SPECIAL:
    n = html.count(old)
    if n == 0: misses.append(('SPECIAL', old))
    html = html.replace(old, new)

for it, en in sorted(TR_SIMPLE, key=lambda p: -len(p[0])):
    pat_old = '>' + it + '<'
    n = html.count(pat_old)
    if n == 0: misses.append(('SIMPLE', it))
    html = html.replace(pat_old, '>' + en + '<')

for tag, distinctive, en in TR_ELEM:
    cnt = html.count(distinctive)
    if cnt != 1:
        misses.append(('ELEM-COUNT(%d)' % cnt, distinctive))
        continue
    pat = re.compile(
        r'(<%s\b[^>]*>)((?:(?!</%s>).)*?%s(?:(?!</%s>).)*?)(</%s>)'
        % (tag, tag, re.escape(distinctive), tag, tag), re.S)
    html, n = pat.subn(lambda m: m.group(1) + en + m.group(3), html, count=1)
    if n == 0: misses.append(('ELEM', distinctive))

html = html.replace('<html lang="it">', '<html lang="en">')
html = html.replace('<button class="lang-btn active" onclick="setLang(\'it\')">IT</button>',
                    '<button class="lang-btn" onclick="setLang(\'it\')">IT</button>')
html = html.replace('<button class="lang-btn" onclick="setLang(\'en\')">EN</button>',
                    '<button class="lang-btn active" onclick="setLang(\'en\')">EN</button>')

open(DST, 'w', encoding='utf-8').write(html)
print('written', DST, len(html), '(src', len(open(SRC, encoding='utf-8').read()), ')')
print('MISSES:', len(misses))
for kind, txt in misses:
    print(' -', kind, '|', txt[:90])
